### ISSUE TITLE
[Todo] 검색 - 이모티콘 검색 시 다른 이모티콘 다 나옴

### ISSUE THREAD

**Issue by yundevingV** [CUK-CRUSH/Server#154]
## 검색
- [x] 이모티콘 검색 시 다른 이모티콘 다 나옴

![image](https://github.com/CUK-CRUSH/Server/assets/91381230/b88a0922-75b5-4409-9900-d6f088be56ae)

**Comment by Feedbaek** [comment]
생각보다 쉽지안은 이슈

**Comment by yundevingV** [comment]
인정합니다..

**Comment by Feedbaek** [comment]
하지만 해결완료
